name_tag: 'test_t1'
gwas:
  filename: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_{gwas_name}.txt.gz'
  cols:
    snpid: 'variant_id'
    effect_allele: 'effect_allele'
    non_effect_allele: 'non_effect_allele'
    zscore: 'zscore'
    allele_frequency: 'frequency'
    sample_size: 'sample_size'
    chr: 'chromosome'
idp_weight:
  filename: '/gpfs/data/im-lab/nas40t2/yanyul/data/brainxcan_data/idp_weights/ridge/original.dmri.parquet'
  cols:
    snpid: 'variant_id'
    effect_allele: 'a1'
    non_effect_allele: 'a0'
    chr: 'chr'
idp_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/misc_data/fourth_round_idp_preprocessing/output/dmri_covar.yaml'
genotype_covariance: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/geno_covar/ukb_idp.geno_cov.chr{chr_num}.banded.npz'
gwas_name: 'GIANT_HEIGHT'
