gwas_tag: 'gtex_gwas'
gwas_file_pattern: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_{gwas_name}.txt.gz'
gwas_name: 'pgc.scz2'

gwas_file_params:
  sample_size: 'sample_size'
  effect_allele: 'effect_allele'
  non_effect_allele: 'non_effect_allele'
  signed_sumstats: 'zscore,0'
  pvalue: 'pvalue'
  snp_col: 'variant_id'

ldsc_repo: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ldsc'

ldscore: 
  dir: '/gpfs/data/im-lab/nas40t2/yanyul/data/eur_w_ld_chr'
  snplist: '/gpfs/data/im-lab/nas40t2/yanyul/data/eur_w_ld_chr/w_hm3.snplist'

idp_tag: 'dmri'
idp_list: 'test_idp_list.txt'
idp_snp_meta: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/subset_genotypes/IDP_HM3_finalPheno.merged_all.bim'
idp_sample_size: 24409
