#PBS -S /bin/bash
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=16
#PBS -l mem=16gb
#PBS -e logs/${NAME}.${CHR}.err
#PBS -o logs/${NAME}.${CHR}.out

source ~/.bash_profile
source ~/.bashrc

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake


conda activate tensorqtl

cd "${PBS_O_WORKDIR}"
pipe=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/gw_qtl/run.snmk


"${SNMK}" -s "${pipe}" \
  --configfile "configs/config.${NAME}.yaml" -p \
  --config \
    chr_num="${CHR}" \
    genotype="${GENO_PATTERN}" \
    outdir="${OUTDIR}" \
  > "${PBS_O_WORKDIR}/logs/${NAME}.${CHR}.log" 2>&1

