gwas_tag: 'group2'
gwas_file_pattern: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/simulation/format_oy_gwas/group2.{gwas_name}.txt.gz'
# gwas_name: ''

gwas_file_params:
  sample_size: 'sample_size'
  effect_allele: 'alt'
  non_effect_allele: 'ref'
  signed_sumstats: 'b,0'
  pvalue: 'pval'
  snp_col: 'variant_id'

ldsc_repo: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ldsc'

ldscore: 
  dir: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/simulation/gen_cor'
  snplist: '/gpfs/data/im-lab/nas40t2/yanyul/data/eur_w_ld_chr/w_hm3.snplist'

# idp_tag: ''
# idp_list: ''
idp_snp_meta: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/subset_genotypes/IDP_HM3_finalPheno.merged_all.bim'
idp_sample_size: 10000

# outdir: ''

