#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=16gb
#PBS -e logs/run_${NAME}_${GWASNAME}_${IDP}.err
#PBS -o logs/run_${NAME}_${GWASNAME}_${IDP}.out

source ~/.bash_profile
source ~/.bashrc

conda activate ldsc

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake


cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/genetic_cor

"${SNMK}" \
  -s run.snmk \
  --configfile "${PBS_O_WORKDIR}/config.${NAME}.yaml" \
  -p all \
  --config gwas_name="${GWASNAME}" \
    idp_tag="${IDP}" \
    idp_list="${PBS_O_WORKDIR}/logs/${IDPLIST}" \
    outdir="${OUTDIR}" \
  > "${PBS_O_WORKDIR}/logs/run_${NAME}_${GWASNAME}_${IDP}.log" \
  2>&1

