---
title: "Heritability of IDPs"
# author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup}
rm(list = ls())
library(ggplot2)
theme_set(theme_bw(base_size = 15))
source('https://gist.githubusercontent.com/liangyy/43912b3ecab5d10c89f9d4b2669871c9/raw/3ca651cfa53ffccb8422f432561138a46e93710f/my_ggplot_theme.R')
library(dplyr)
options(stringsAsFactors = F)
library(patchwork)
source('rlib.R')
```

# About

Here I ran heritability estimation using EMMA based approach (see [pyemma at here](https://github.com/liangyy/misc-tools/tree/master/pyemma)).

# Load data

Load heritability estimates done by Owen.
And merge with the my results.

```{r}
df_h2_owen = read.table('~/Desktop/tmp/ukb_idp/owen_heritability/2020-08-11_idp-heritability-estimates.txt.gz', header = T)
df_h2 = read.delim('~/Desktop/tmp/ukb_idp/heritability/pyemma.idp_original.tsv.gz')
df_merge = inner_join(df_h2_owen, df_h2, by = c('gene' = 'phenotype'))
df_merge %>% ggplot() +
  geom_errorbar(aes(x = Variance, ymin = h2 - h2_SE * 1.96, ymax = h2 + h2_SE * 1.96), color = 'gray') + 
  geom_errorbarh(aes(xmin = Variance - SE * 1.96, xmax = Variance + SE * 1.96, y = h2), color = 'gray') +
  geom_point(aes(x = Variance, y = h2), alpha = 0.2) + th + 
  geom_abline(slope = 1, intercept = 0) +
  coord_equal() +
  xlab('h2 (Owen)') +
  ylab('h2 (new run)')
```

Load a few GCTA runs.

```{r}
ll = list()
for(idp in unique(df_merge$gene)) {
  fn = paste0('~/Desktop/tmp/ukb_idp/heritability/gcta_out.', idp, '.hsq')
  if(file.exists(fn)) {
    ll[[length(ll) + 1]] = load_gcta_hsq(fn) %>% mutate(phenotype = idp)
  }
}
df_gcta = do.call(rbind, ll)
df_gcta = inner_join(df_merge, df_gcta, by = c('gene' = 'phenotype'), suffix = c('.pyemma', '.gcta'))
df_gcta %>% ggplot() + geom_errorbar(aes(x = h2.gcta, ymin = h2.pyemma - h2_SE.pyemma * 1.96, ymax = h2.pyemma + h2_SE.pyemma * 1.96), color = 'gray') + 
  geom_errorbarh(aes(xmin = h2.gcta - h2_SE.gcta * 1.96, xmax = h2.gcta + h2_SE.gcta * 1.96, y = h2.pyemma), color = 'gray') +
  geom_point(aes(x = h2.gcta, y = h2.pyemma), alpha = 0.2) + th + 
  geom_abline(slope = 1, intercept = 0) +
  coord_equal() +
  xlab('h2 (gcta)') +
  ylab('h2 (pyemma)')
```

Load the heritability runs with different number of PCs being regressed out.

```{r}
npcs = c(0, 1, 2, 5, 10, 20, 50)
df_pc = list()
for(pc in npcs) {
  tmp = read.table(paste0('~/Desktop/tmp/ukb_idp/heritability/pyemma.idp_pc', pc, '.tsv.gz'), header = T)
  df_pc[[length(df_pc) + 1]] = tmp %>% mutate(npc = pc)
}
df_pc = do.call(rbind, df_pc)
```

```{r}
df_pc$npc = factor(df_pc$npc, levels = unique(df_pc$npc))
df_pc2 = reshape2::dcast(rbind(df_pc, df_h2 %>% mutate(npc = 'original')), phenotype ~ npc, value.var = 'h2')
pairs(df_pc2[, -1], main = 'Pairwise comparison of h2 for differnt nPC')
```

```{r, fig.height=8, fig.width=4}
df_pc %>% ggplot() + geom_histogram(aes(x = h2)) + facet_wrap(~npc, ncol = 1, labeller = label_both) + th2
```

# dMRI new data (after PCA)

```{r}
dmri_annot = readRDS('../misc_data/download_some_matching_files/annot_dmri_idps.rds')
dmri_annot$idp = paste0('IDP-', dmri_annot$FieldID)
dmri_annot = dmri_annot %>% select(idp, type, position, measure, lr)
df_dmri = read.table('~/Desktop/tmp/ukb_idp/heritability/pyemma.idp_dmri.tsv.gz', header = T)
df_dmri = df_dmri %>% mutate(type = unlist(lapply(strsplit(phenotype, '-'), function(x){x[[1]]}))) %>% 
   mutate(type2 = unlist(lapply(strsplit(phenotype, '-'), function(x){as.numeric(x[[2]])})))
df_dmri %>% filter(type == 'IDP') %>% ggplot() + 
  geom_histogram(aes(x = h2)) + 
  geom_vline(data = df_dmri %>% filter(type == 'PC'), aes(xintercept = h2)) +
  geom_label(data = df_dmri %>% filter(type == 'PC'), aes(x = h2, y = type2 * 5, label = phenotype)) + th
```

```{r}
tmp = inner_join(df_dmri, df_h2, by = 'phenotype', suffix = c('.dmri', '.original'))
tmp = inner_join(tmp, dmri_annot, by = c('phenotype' = 'idp'))
tmp %>% ggplot() + geom_point(aes(x = h2.original, y = h2.dmri, color = measure), alpha = 0.5) + 
  th + geom_abline(slope = 1, intercept = 0) +
  stat_ellipse(aes(x = h2.original, y = h2.dmri, color = measure, group = measure),type = "norm")
tmp %>% select(phenotype, measure, lr, position, h2.original, h2.dmri) %>% 
  reshape2::melt(id.var = c('phenotype', 'measure', 'lr', 'position')) %>% 
  ggplot() + geom_density(aes(x = value, fill = measure), alpha = 0.5) + 
  th2 + 
  facet_wrap(~variable, ncol = 1)
tmp %>% select(phenotype, measure, lr, position, h2.original, h2.dmri) %>% 
  reshape2::melt(id.var = c('phenotype', 'measure', 'lr', 'position')) %>% 
  ggplot() + geom_boxplot(aes(x = position, y = value, fill = variable), alpha = 0.5) + 
  th + theme(legend.position = 'bottom')
tmp %>% filter(!is.na(lr)) %>% select(type.y, measure, position, lr, h2.original, h2.dmri) %>% reshape2::dcast(type.y + measure + position ~ lr, value.var = 'h2.original') %>%
  ggplot() + geom_point(aes(x = left, y = right), alpha = 0.4) + th + coord_equal() +
  geom_abline(slope = 1, intercept = 0) + ggtitle('h2.original')
tmp %>% filter(!is.na(lr)) %>% select(type.y, measure, position, lr, h2.original, h2.dmri) %>% reshape2::dcast(type.y + measure + position ~ lr, value.var = 'h2.dmri') %>%
  ggplot() + geom_point(aes(x = left, y = right), alpha = 0.4) + th + coord_equal() +
  geom_abline(slope = 1, intercept = 0) + ggtitle('h2.dmri')
```