---
title: "Analysis"
# author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

* Genome-wode ridge regression (with comparison to Owen's result) [link](gw_ridge.html)
* Compare `snpnet` lasso (old code and updated code) [link](gw_lasso_update.html)
* ImageXcan round 1:
    - [dMRI](imagexcan_round_1_dmri.html)
    - [T1](imagexcan_round_1_t1.html)
    - [T1 EN vs ridge](imagexcan_round_1_t1_en_vs_ridge.html)
* Downstream Mendelian randomization:
    - An example run with cigarette intake and IDP-25882 [link](example_mr.html)

* S-ImageXcan results:
    - [GTEx-GWAS phenotypes](simagexcan_gtex_gwas.html)

* Summary of current runs on GTEx-GWAS phenotypes (S-ImageXcan) and a selected set of phenotypes (ImageXcan): [link](summary_121520.html)

* The 2nd round of analysis
    - Heritability [link](round_2_h2.html)
    - Cross-validated performance (Spearman's correlation) [link](round_2_cv_perf.html)
    - Overview of all the results for GTEx-GWAS phenotypes [link](round_2_gtex_gwas.html)
    - Selected `scaled.T1` and `original.dMRI` results for GTEx-GWAS phenotypes [link](round_2_gtex_gwas_selected.html)

* Psychiatric traits [link](simagexcan_psychiatric.html)

