---
title: "Summary BrainXcan runs on psychiatric traits"
# author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup}
rm(list = ls())
library(ggplot2)
theme_set(theme_bw(base_size = 15))
source('https://gist.githubusercontent.com/liangyy/43912b3ecab5d10c89f9d4b2669871c9/raw/3ca651cfa53ffccb8422f432561138a46e93710f/my_ggplot_theme.R')
source('https://raw.githubusercontent.com/liangyy/misc-tools/master/plot_tool/plot_tools.R')
library(dplyr)
options(stringsAsFactors = F)
library(patchwork)
library(data.table)
options(datatable.fread.datatable = F)
source('rlib.R')
library(ggpubr)
library(pander)
panderOptions("table.split.table", Inf)

```

# About

Here we ran S-BrainXcan on psychiatric traits listed [here](https://docs.google.com/spreadsheets/u/1/d/1QHpA1IZwTt-3Dx4zvfRXycztS9DPhKAN3Mzw5EBB840).

# Load results

```{r}
pheno_list = read.table('../misc_data/preprocess_psychiatric_traits/trait_list.txt', header = F)$V1
df = list()
for(idp_type in c('dmri', 't1')) {
  for(method in c('en', 'ridge')) {
    for(p in pheno_list) {
      fn = paste0('~/Desktop/tmp/ukb_idp/simagexcan/results_psychiatric/', idp_type, '_', method, '_x_', p, '_x_simagexcan.csv')
      if(file.exists(fn)) {
        tmp = read.csv(fn)
        df[[length(df) + 1]] = tmp %>% mutate(phenotype = p, idp_type = idp_type, method = method)
      }
    }
  }
}

df = do.call(rbind, df)
```

Load dMRI and T1 IDP annotations.

```{r}
t1 = readRDS('../misc_data/process_t1/t1_meta.rds')
t1 = t1 %>% mutate(IDP = paste0('IDP-', FieldID))
dmri = readRDS('../misc_data/download_some_matching_files/annot_dmri_idps.rds')
dmri = dmri %>% mutate(IDP = paste0('IDP-', FieldID))
idps = c('t1', 'dmri')
df_annot = rbind(
  t1 %>% select(IDP, Field),
  dmri %>% select(IDP, Field)
)
```

# QQ-plot

```{r}
qqplot_by_group(df$pval, group = paste(df$idp_type, df$method)) + th 
```

# PIP

```{r, fig.width=8, fig.height=6}
df %>% ggplot() + geom_jitter(aes(x = phenotype, y = pip, color = factor(cs95)), width = 0.3, height = 0, alpha = 0.2) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + th2 + facet_wrap(~idp_type, ncol = 1)
```

# Bonferroni significant

```{r}
df = df %>% mutate(p_adj = pval * n())
bonferroni_cutoff = 0.001
message('There are ', df %>% filter(p_adj < bonferroni_cutoff) %>% nrow, ' IDP-phenotype pairs passed Bonferroni significance cutoff at ', bonferroni_cutoff)
```

# 95% Credible set

```{r}
message('There are ', df %>% filter(cs95 > 0) %>% nrow, ' IDP-phenotype pairs within 95% credible set')
```

# Obtain the list of candidate signals

Here we focus on the phenotypes with at least one hit within 95% credible set OR Bonferroni significant at $\alpha = 0.001$.

```{r}
df_cs = df %>% filter(cs95 > 0)
df_bon = df %>% filter(p_adj < bonferroni_cutoff)
df_signif = rbind(df_cs, df_bon) %>% distinct()
df_signif_t1 = df_signif %>% filter(idp_type == 't1') %>% mutate(phenotype2 = phenotype) %>% select(phenotype, phenotype2, IDP) %>% distinct_all
colnames(df_signif_t1) = c('pheno', 'pheno_code', 'idp')
df_signif_dmri = df_signif %>% filter(idp_type == 'dmri') %>% mutate(phenotype2 = phenotype) %>% select(phenotype, phenotype2, IDP) %>% distinct_all
colnames(df_signif_dmri) = c('pheno', 'pheno_code', 'idp')
write.table(df_signif_t1, '../misc_data/simagexcan_psychiatric.t1.signif.tsv', quo = F, col = T, row = F, sep = '\t')
write.table(df_signif_dmri, '../misc_data/simagexcan_psychiatric.dmri.signif.tsv', quo = F, col = T, row = F, sep = '\t')
```

# MR results

```{r}
collector_mr = list()
collector_data = list()
df_signif_unique = df_signif %>% select(idp_type, IDP, phenotype) %>% distinct()
sub = df_signif_unique
for(i in 1 : nrow(df_signif_unique)) {
  fn = paste0('~/Desktop/tmp/ukb_idp/mr_psychiatric/MR_local.psychiatric_', df_signif_unique$idp_type[i], '.', df_signif_unique$IDP[i], '_x_', df_signif_unique$pheno[i], '.rds')
  if(!file.exists(fn)) {
    next
  }
  tmp = readRDS(fn)
  if(sum(is.na(tmp$idp2pheno$mr)) == 1 | sum(is.na(tmp$pheno2idp$mr)) == 1) {
    next
  }
  n_idp2pheno = sum(tmp$idp2pheno$mr$pval < 0.05) 
  n_pheno2idp = sum(tmp$pheno2idp$mr$pval < 0.05) 
  if(n_idp2pheno > 2 | n_pheno2idp > 2) {
    collector_mr[[length(collector_mr) + 1]] = rbind(
      tmp$idp2pheno$mr %>% mutate(direction = 'idp2pheno', pheno = sub$phenotype[i], IDP = sub$IDP[i], is_forward = n_idp2pheno > 3, is_pass = n_idp2pheno > 3 | n_pheno2idp > 3),
      tmp$pheno2idp$mr %>% mutate(direction = 'pheno2idp', pheno = sub$phenotype[i], IDP = sub$IDP[i], is_forward = n_idp2pheno > 3, is_pass = n_idp2pheno > 3 | n_pheno2idp > 3)
    )
    collector_data[[length(collector_data) + 1]] = rbind(
      tmp$idp2pheno$data %>% select(beta.exposure, beta.outcome, pval.exposure) %>% mutate(direction = 'idp2pheno', pheno = sub$phenotype[i], IDP = sub$IDP[i], is_forward = n_idp2pheno > 3, is_pass = n_idp2pheno > 3 | n_pheno2idp > 3),
      tmp$pheno2idp$data %>% select(beta.exposure, beta.outcome, pval.exposure) %>% mutate(direction = 'pheno2idp', pheno = sub$phenotype[i], IDP = sub$IDP[i], is_forward = n_idp2pheno > 3, is_pass = n_idp2pheno > 3 | n_pheno2idp > 3)
    )
  }
}
df_data = do.call(rbind, collector_data) %>% inner_join(df_annot, by = 'IDP')
df_mr = do.call(rbind, collector_mr) %>% inner_join(df_annot, by = 'IDP')
```

The selected MR pairs.

```{r}
df_all_signif = df
plot_pair = function(pheno_, idp_) {
  mydat = df_data %>% filter(pheno == pheno_, IDP == idp_)
  mymr = df_mr %>% filter(pheno == pheno_, IDP == idp_)
  idp_name = mydat$Field[1]
  gwas_name = mydat$pheno[1]
  idp_id = mydat$IDP[1]
  this_result = df_all_signif %>% filter(IDP == idp_id, phenotype == gwas_name)
  plist = list()
  plist[[length(plist) + 1]] = mydat %>% filter(direction == 'idp2pheno') %>% ggplot() + 
    geom_point(aes(x = beta.exposure, y = beta.outcome, size = -log10(pval.exposure)), alpha = 0.2) + 
    geom_vline(xintercept = 0, color = 'lightgray') + 
    geom_hline(yintercept = 0, color = 'lightgray') + th + ggtitle(paste0(idp_name, ' -> \n ', gwas_name)) +
    theme(legend.position = 'none') # +
  # geom_abline(data = this_result, aes(slope = bhat, intercept = 0, color = model))
  plist[[length(plist) + 1]] = mydat %>% filter(direction == 'pheno2idp') %>% ggplot() + geom_point(aes(x = beta.exposure, y = beta.outcome, size = -log10(pval.exposure)), alpha = 0.2) + geom_vline(xintercept = 0, color = 'lightgray') + geom_hline(yintercept = 0, color = 'lightgray') + th + ggtitle(paste0(gwas_name, ' -> \n ', idp_name)) +
    theme(legend.position = 'none') # +
  # geom_abline(data = this_result, aes(slope = 1 / bhat, intercept = 0, color = model))
  # plist[[length(plist) + 1]] = gridExtra::tableGrob(df_mr %>% select(method, nsnp, b, pval, direction))
  this_result2 = this_result %>% mutate(method = paste0('imgx_', method), nsnp = paste0('pip = ', signif(pip, digits = 2), '\n cs = ', cs95), b = bhat, direction = NA) 
  mymr = rbind(mymr %>% select(method, nsnp, b, pval, direction), this_result2 %>% select(method, nsnp, b, pval, direction))
  qq = ggarrange(plist[[1]], plist[[2]], ggtexttable(format(mymr, digits = 3)), ncol = 3)
  qq
}
# df_mr %>% select(pheno, IDP) %>% distinct() %>% pander::pander()
df_tmp = df_mr %>% select(pheno, IDP) %>% distinct()
```

Show the plot.

```{r, fig.width=15, fig.height=5}
for(i in 1 : nrow(df_tmp)) {
  qq = plot_pair(df_tmp$pheno[i], df_tmp$IDP[i])
  print(qq)
}
```
