name_tag: 'PLACEHOLDER'
tensorqtl_path: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/tensorqtl/tensorqtl'
misc_tools_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/pyutil'
wrapper_script: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/gw_qtl/run_trans_qtl.py'
genotype: '/gpfs/data/im-lab/nas40t2/festus/metabolomics/guardian/MetaboXcan/brainxcan/genotype/train/IDP_HM3_finalPheno.chr{chr_num}.bed'

phenotype:
  table: '/gpfs/data/im-lab/nas40t2/festus/brainxcan/genotype/train/PLACEHOLDER.parquet'
  indiv_col: 'individual'
map_trans_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/gwas/map_trans.yaml'
ncores: 16
outdir: '/scratch/fnyasimi1/ukb_idp/idp_gwas_4th'
