#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=5
#PBS -l mem=64gb
#PBS -e ${OUTDIR}/pred_idp.err
#PBS -o ${OUTDIR}/pred_idp.out



source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

bgen=/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/imagexcan_test_run/geno_for_test.chr{chr_num}.bgen
bgi=/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/imagexcan_test_run/geno_for_test.chr{chr_num}.bgen.bgi
sample_prefix=/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/imagexcan_test_run/geno_for_test.chr

prs_parquet=/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/imagexcan_test_run/idp_weights.parquet


nthread=2
ukb_imp_reader_path=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/bgen_io

output_prefix=/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/imagexcan_test_run/pred_idp.chr

for chr in `seq 21 22`
do
  python /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/prediction/run_prs.py \
    --ukb_bgen_pattern $bgen \
    --ukb_bgi_pattern $bgi \
    --ukb_sample_file $sample_prefix$chr.sample \
    --prs_parquet $prs_parquet \
    --nthread $nthread \
    --output $output_prefix$chr.parquet \
    --chromosomes $chr \
    --ukb_imp_reader_path $ukb_imp_reader_path > \
    /gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/imagexcan_test_run/pred_idp.chr$chr.log 2>&1
done
