name_tag: 'PLACEHOLDER'
tensorqtl_path: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/tensorqtl/tensorqtl'
misc_tools_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/pyutil'
wrapper_script: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/gw_qtl/run_trans_qtl.py'
genotype: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/subset_genotypes/IDP_HM3_finalPheno.chr{chr_num}.bed'

phenotype: 
  table: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/third_round_idp_preprocessing/PLACEHOLDER.parquet'
  indiv_col: 'individual'
map_trans_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/gwas/map_trans.yaml'
ncores: 16
outdir: '/scratch/t.cri.yliang/ukb_idp/idp_gwas_3rd'
