genome_build: 'hg19'

variant_id: 'SNP'
chromosome: 'CHR'
position: 'BP'
effect_allele: 'A1'
non_effect_allele: 'A2'
zscore: 'Z'
pvalue: 'P'
sample_size: 'Weight'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/pgc_alcdep.eur_discovery.aug2018_release.txt.gz'

extra_command:
  - '-meta_extra_col rsid:6'
  - "separator ' '"
