genome_build: 'hg19'

variant_id: 'RSID'
chromosome: 'CHR'
position: 'POS'
effect_allele: 'Tested_Allele'
non_effect_allele: 'Other_Allele'
frequency: 'EAF_UKB'
zscore: 'Z'
pvalue: 'P'
sample_size: 'N'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/Meta-analysis_Locke_et_al+UKBiobank_2018_UPDATED.txt.gz'
