genome_build: 'hg19'

variant_id: 'MarkerName'
chromosome: 'CHR'
position: 'POS'
effect_allele: 'A1'
non_effect_allele: 'A2'
frequency: 'EAF'
effect_size: 'Beta'
effect_se: 'SE'
pvalue: 'Pval'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/GWAS_EA_excl23andMe.txt'
