genome_build: 'hg19'

variant_id: 'ID'
chromosome: 'CHROM'
position: 'POS'
effect_allele: 'ALT'
non_effect_allele: 'REF'
effect_size: 'BETA'
effect_se: 'SE'
pvalue: 'PVAL'
sample_size_half: 'NEFFDIV2'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/pgcAN2.2019-07.vcf.tsv.gz'
