genome_build: 'hg19'

variant_id: 'ID'
chromosome: 'CHROM'
position: 'POS'
effect_allele: 'ALT'
non_effect_allele: 'REF'
effect_size: 'BETA'
effect_se: 'SE'
pvalue: 'PVAL'
sample_size: 'NEFFDIV2_x_2'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/cleaned_pgcAN2.2019-07.tsv.gz'


extra_command:
  - '-meta_extra_col rsid:6 reference_frequency:5'
  - '--chromosome_format'
