genome_build: 'hg19'

variant_id: 'SNP'
chromosome: 'CHR'
position: 'POS'
effect_allele: 'A1'
non_effect_allele: 'A2'
frequency: 'Freq_Tested_Allele_in_HRS'
effect_size: 'BETA'
effect_se: 'SE'
pvalue: 'P'
sample_size: 'N'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/sumstats_neuroticism_ctg_format.txt.gz'
