genome_build: 'hg19'

chr_pos: 
  col: 'SNP'
  sep: ':'
  
effect_allele: 'A1'
non_effect_allele: 'A2'
frequency: 'freq'
effect_size: 'b'
effect_se: 'se'
zscore: 'Z'
pvalue: 'p'
ncase: 'N_cases'
ncontrol: 'N_controls'

file_path: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/raw/nallsEtAl2019_excluding23andMe_allVariants.tab.zip'
