#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=32gb
#PBS -l nodes=1:ppn=12
#PBS -e logs/run_${NAME}.err
#PBS -o logs/run_${NAME}.out

source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

# load extra python dependency
export PYTHONPATH=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/simagexcan:$PYTHONPATH

cd "${PBS_O_WORKDIR}"

if [[ -z "${EXTRA_ARG}" ]]; then
  python calc_inflation_from_ld.py \
    --genotype_covariance "${GENO_PATTERN}" \
    --output "${OUTDIR}/${NAME}.tsv"
else
  python calc_inflation_from_ld.py \
    --genotype_covariance "${GENO_PATTERN}" \
    --output "${OUTDIR}/${NAME}.tsv" \
    "${EXTRA_ARG}"
fi

  
