#PBS -S /bin/bash
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -e logs/debug.err
#PBS -o logs/debug.out
#PBS -N debug_gw_lasso


source ~/.bash_profile
source ~/.bashrc

conda activate snpnet

cd ${PBS_O_WORKDIR}
cd ../../methods/gw_lasso

outdir=/scratch/t.cri.yliang/ukb_idp/debug_gw_lasso_2
mkdir -p $outdir

Rscript run_gw_lasso_debug.R \
  --genotype /gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/subset_genotypes/IDP_HM3_finalPheno.merged_all \
  --phenotype_table /scratch/t.cri.yliang/ukb_idp/gw_lasso/batch036.phe.tsv \
  --nfold 5 \
  --inner_nfold 5 \
  --indiv_col individual \
  --pheno_list /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/gw_lasso/debug.pheno_list.txt \
  --snpnet_config /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/gw_lasso/snpnet.yaml  \
  --output_prefix $outdir/debug \
  --mem 8000 \
  --alpha 1 > $outdir/debug.log
