#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=32gb
#PBS -e logs/format_gwas_${NAME}_${GWASNAME}.err
#PBS -o logs/format_gwas_${NAME}_${GWASNAME}.out

source ~/.bash_profile
source ~/.bashrc

conda activate ldsc

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake


cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/genetic_cor

$SNMK -s run.snmk --configfile ${PBS_O_WORKDIR}/config.$NAME.yaml -p all_gwas --config gwas_name=$GWASNAME gwas_tag=$NAME > ${PBS_O_WORKDIR}/logs/format_gwas_${NAME}_${GWASNAME}.log 2>&1

