outdir: '/scratch/t.cri.yliang/ukb_idp/simagexcan/results_psychiatric'
name_tag: 'dmri_en'
gwas:
  filename: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/formatted/harmonized_gwas.{gwas_name}.tsv.gz'
  cols:
    snpid: 'rsid'
    effect_allele: 'effect_allele'
    non_effect_allele: 'non_effect_allele'
    effect_size: 'effect_size'
    standard_error: 'standard_error'
    chr: 'chromosome'
idp_weight:
  filename: '/scratch/t.cri.yliang/ukb_idp/gw_elastic_net_dmri/gw_lasso_beta.parquet'
  cols:
    snpid: 'variant_id'
    effect_allele: 'a0'
    non_effect_allele: 'a1'
    chr: 'chr'
genotype_covariance: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/simagexcan/output/ukb_idp.geno_cov.chr{chr_num}.banded.npz'
gwas_list: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/misc_data/preprocess_psychiatric_traits/trait_list.txt'
