name_tag: 'dmri_gtex_gwas'
gwas:
  filename: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_{gwas_name}.txt.gz'
  cols:
    snpid: 'variant_id'
    effect_allele: 'effect_allele'
    non_effect_allele: 'non_effect_allele'
    zscore: 'zscore'
    allele_frequency: 'frequency'
    sample_size: 'sample_size'
    chr: 'chromosome'
idp_weight:
  filename: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/gw_ridge/gw_ridge_beta.dmri.default_theta_g_fold_5_5.parquet'
  cols:
    snpid: 'variant_id'
    effect_allele: 'a0'
    non_effect_allele: 'a1'
    chr: 'chr'
genotype_covariance: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/simagexcan/output/ukb_idp.geno_cov.chr{chr_num}.banded.npz'
gwas_list: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/simagexcan/gtex_gwas_list.txt'