#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=12
#PBS -l mem=64gb
#PBS -e logs/run_simgx_${NAME}.err
#PBS -o logs/run_simgx_${NAME}.out

# t1: ppn=12
# dmri: ppn=2

source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake

# load extra python dependency
export PYTHONPATH=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/pyutil
export PYTHONPATH=/gpfs/data/im-lab/nas40t2/yanyul/softwares/tensorqtl/tensorqtl:$PYTHONPATH
export PYTHONPATH=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/gw_ridge:$PYTHONPATH
export PYTHONPATH=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/imagexcan:$PYTHONPATH

cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/simagexcan

$SNMK -s run.snmk --configfile ${PBS_O_WORKDIR}/config.$NAME.yaml --cores 12 > ${PBS_O_WORKDIR}/logs/run_simgx_${NAME}.log 2>&1

