#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=16gb
#PBS -l nodes=1:ppn=16
#PBS -e logs/run_bxcan_permz_${CONFIGNAME}.err
#PBS -o logs/run_bxcan_permz_${CONFIGNAME}.out

export RSTUDIO_PANDOC=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/r_36/bin

BXCAN=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/brainxcan

# load plink1.9
module load gcc/6.2.0
module load plink/1.90

# load conda 
source ~/.bash_profile
source ~/.bashrc

conda activate brainxcan

export PYTHONPATH=$BXCAN:$PYTHONPATH

cd "${PBS_O_WORKDIR}"

snakemake -s "${BXCAN}/brainxcan/snmk/run.snmk" \
  --configfile "${PBS_O_WORKDIR}/config.${CONFIGNAME}.yaml" \
  -p SBrainXcanOnly --cores 5 --nt \
  --config brainxcan_path="${BXCAN}" prefix="${GWASNAME}" outdir="${OUTDIR}" \
  > "${PBS_O_WORKDIR}/logs/run_bxcan_permz_${CONFIGNAME}_${GWASNAME}.log" \
  2>&1

