# gwas_tag: 'IDP-25109'
gwas_parquet: '/project2/haky/Data/BrainXcan/idp_gwas_4th/trans_qtl.fourth_round.t1_w_pc.chr{chr_num}/{gwas_tag}.parquet'
gwas_formatted: '{outdir}/{gwas_tag}.formated_gwas.mat'
gwas_mode: ''
outdir: '/scratch/midway2/yanyul/ukb_idp/ld4m/fourth_round_t1'

SLD4M: 
  path_to_scripts: '/project2/haky/yanyul/github_external/SLD4M'
  l2l4: '/project2/haky/yanyul/data/SLD4M/baselineLD.1kg.l2l4.mat'
path_to_run_script: '/project2/haky/yanyul/GitHub/misc-tools/est_polygenicity/scripts'
