#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -e logs/run_sbayess_$IDP.err
#PBS -o logs/run_sbayess_$IDP.out

source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake


cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/est_polygenicity

$SNMK -s sbayess.snmk \
  --configfile ${PBS_O_WORKDIR}/config.sbayess_run.yaml \
  ${PBS_O_WORKDIR}/logs/run_sbayess_$IDP.log 2>&1

