#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -e logs/run_sbayess_${CONFIG}_${IDP}.err
#PBS -o logs/run_sbayess_${CONFIG}_${IDP}.out
#PBS -l mem=16gb
#PBS -l walltime=48:00:00

source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake


cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/est_polygenicity

$SNMK -s sbayess.snmk \
  --configfile ${PBS_O_WORKDIR}/config.$CONFIG.yaml > \
  ${PBS_O_WORKDIR}/logs/run_sbayess_${CONFIG}_${IDP}.log 2>&1

