gwas: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/formatted/harmonized_gwas.{prefix}.tsv.gz'  
datadir: '/gpfs/data/im-lab/nas40t2/yanyul/data/brainxcan_data'
outdir: '~/psychiatric_permz_rerun'
# prefix: 'SCZ_PGC_2020'
# brainxcan_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/brainxcan'

gwas_pop: 'EUR'
snpid: 'rsid'
effect_allele: 'effect_allele'
non_effect_allele: 'non_effect_allele'
effect_size: 'effect_size'
effect_size_se: 'standard_error'
chr: 'chromosome'
zscore: 'zscore'
sample_size: 'sample_size'
allele_frequency: 'frequency'
position: 'position'


# model_type: 'ridge'
idp_type: 'residual'
signif_pval: 1e-4
signif_max_idps: 20
# ld_clump_yaml: '{datadir}/mr/ld_clump.yaml'
     
rscript_exe: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/r_36/bin/Rscript' 
# python_exe: 'python'

bxcan_ldblock_perm: '/gpfs/data/im-lab/nas40t2/yanyul/data/ldblock/fourier_ls-all.bed'
