#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=64gb
#PBS -l nodes=1:ppn=6
#PBS -e logs/${CONFIGNAME}_${PHENOTYPE}.err
#PBS -o logs/${CONFIGNAME}_${PHENOTYPE}.out


# args1: PHENOTYPE
# args2: CONFIGNAME

export RSTUDIO_PANDOC=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/r_36/bin

BXCAN=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/brainxcan

# load plink1.9
module load gcc/6.2.0
module load plink/1.90

# load conda 
source ~/.bash_profile
source ~/.bashrc

conda activate brainxcan

export PYTHONPATH=$BXCAN:$PYTHONPATH

cd ${PBS_O_WORKDIR}

snakemake -s $BXCAN/brainxcan/snmk/run.snmk \
  --configfile ${PBS_O_WORKDIR}/config.$CONFIGNAME.yaml \
  -p SBrainXcanOnly --cores 5 --nt --forceall \
  --config brainxcan_path=$BXCAN prefix=$PHENOTYPE \
  > ${PBS_O_WORKDIR}/logs/${CONFIGNAME}_${PHENOTYPE}.log 2>&1


