#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=64gb
#PBS -e logs/${CONFIGNAME}_${PHENOTYPE}.err
#PBS -o logs/${CONFIGNAME}_${PHENOTYPE}.out


# args1: PHENOTYPE
# args2: CONFIGNAME


module load gcc/6.2.0

# set standalone R dependencies
module load R/3.6.4
export R_LIBS=$R_LIB:~/labshare/softwares/rlib/3.6/

BXCAN=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/brainxcan
CONFIGPATH=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/misc_data/supplementary_materials_4th/run_brainxcan

# load plink1.9
module load plink/1.90

# load conda 
module load conda

conda activate brainxcan

snakemake -s $BXCAN/brainxcan/snmk/run.snmk \
  --configfile $CONFIGPATH/config.$CONFIGNAME.yaml \
  -p SBrainXcan -j5 --config \
  brainxcan_path=$BXCAN \    
  prefix=$PHENOTYPE > logs/${CONFIGNAME}_${PHENOTYPE}.log 2>&1
