outdir: '/vol/bmd/yanyul/UKB/ukb_idp_genetic_arch/subset_plink_bed'
name_tag: 'IDP_HM3_finalPheno'

plink1.9: '/vol/bmd/yanyul/softwares/plink'
plink_mem_in_mb: 10000
snplist: '/vol/bmd/yanyul/UKB/ukb_idp_genetic_arch/hapmap3_eur_snplist/hapmap3_eur_pop_CEU_maf_0.01.txt'
indivlist: '/vol/bmd/yanyul/UKB/ukb_idp_genetic_arch/final_phenotype_indivlist/2020-05-18_final-phenotypes.indiv_list.txt'
genotype_bed: '/vol/bmd/meliao/data/genotype/plink/chr-{chr_num}'
  
