#PBS -S /bin/bash
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=16gb
#PBS -e logs/${NAME}.err
#PBS -o logs/${NAME}.out

source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

cd "${PBS_O_WORKDIR}"

python format_oy_gwas.py \
  --pheno_list "${PHENO_LIST}" \
  --input_pattern "${INPUT_PATTERN}" \
  --snp_bim_pattern "${SNP_BIM_PATTERN}" \
  --output_pattern "${OUTPUT_PATTERN}" \
  --sample_size "${SAMPLE_SIZE}" \
  > "logs/${NAME}.log" 2>&1

