name_tag: 'psychiatric_2nd_dmri'
idp_pheno_table: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/misc_data/round_2_selected.psychiatric.dmri.signif.tsv'
idp_type: 'dmri.original.all_covar.w_pc'

ld_clump_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/mr/ld_clump2.yaml'
idp_gwas_pattern: '/scratch/t.cri.yliang/ukb_idp/idp_gwas_2nd/trans_qtl.{idp_type}.chr{chr_num}/{idp}.parquet'
snp_bim: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/subset_genotypes/IDP_HM3_finalPheno.chr{chr_num}.bim'

outdir: '/scratch/t.cri.yliang/ukb_idp/mr_psychiatric_2nd'


gwas_file_pattern: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/psychiatric_gwas/formatted/harmonized_gwas.{gwas_name}.tsv.gz'
gwas_yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/submission/mr/psychiatric.gwas.yaml'


