#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=64gb
#PBS -l nodes=1:ppn=12
#PBS -e logs/run_${NAME}.err
#PBS -o logs/run_${NAME}.out

source ~/.bash_profile
source ~/.bashrc

conda activate ukb_idp

cd "${PBS_O_WORKDIR}"

export PYTHONPATH=/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ukb_idp_genetic_arch/methods/simagexcan:$PYTHONPATH

python calc_assoc.py \
  --genotype_covariance "${GENO_COVAR_PATTERN}" \
  --b1 "${B1}" \
  --b2 "${B2}" \
  --b1_effs "${B1_LIST}" \
  --b2_effs "${B2_LIST}" \
  --output "${OUTPUT}" \
  > "${PBS_O_WORKDIR}/run_${NAME}.log" \
  2>&1
